updates

diff --git a/bin/mapreduce b/bin/mapreduce
--- a/bin/mapreduce
+++ b/bin/mapreduce
@@ -52,11 +52,13 @@ case $1 in
         echo '{"message_type": "shutdown"}' | $NC localhost 6000 || true
         sleep 2  # give the manager time to receive signal and send to workers
         
-        if pgrep -f mapreduce-manager &> /dev/null; then
+        if pgrep -f mapreduce-manager &> /dev/null; 
+        then
             echo "killing mapreduce manager ..."
             pkill -f mapreduce-manager || true
         fi
-        if pgrep -f mapreduce-worker &> /dev/null; then
+        if pgrep -f mapreduce-worker &> /dev/null; 
+        then
             echo "killing mapreduce worker ..."
             pkill -f mapreduce-worker || true
         fi
@@ -84,8 +86,47 @@ case $1 in
         fi
         ;;
     "restart")
-        mapreduce stop
-        mapreduce start
+        echo "stopping mapreduce ..."
+        set +o pipefail  # Avoid erroneous failures due to grep returning non-zero
+        if nc -h 2>&1 | grep -q "\-c"; then
+            NC="nc -c"
+        elif nc -h 2>&1 | grep -q "\-N"; then
+            NC="nc -N"
+        elif nc -h 2>&1 | grep -q "\-C"; then
+            NC="nc -C"
+        else
+        echo "Error detecting netcat version."
+        exit 1
+        fi
+        set -o pipefail
+        echo '{"message_type": "shutdown"}' | $NC localhost 6000 || true
+        sleep 2  # give the manager time to receive signal and send to workers
+        if pgrep -f mapreduce-manager &> /dev/null; 
+        then
+            echo "killing mapreduce manager ..."
+            pkill -f mapreduce-manager || true
+        fi
+        if pgrep -f mapreduce-worker &> /dev/null; 
+        then
+            echo "killing mapreduce worker ..."
+            pkill -f mapreduce-worker || true
+        fi
+
+        if pgrep -f mapreduce-manager &> /dev/null;  
+        then
+            echo "Error: mapreduce-manager is already running"
+            exit 1
+        elif pgrep -f mapreduce-worker &> /dev/null; 
+        then
+            echo "Error: mapreduce-worker is already running"
+            exit 1
+        else
+            echo "starting mapreduce ..."
+            mapreduce-manager --host localhost --port 6000 --hb-port 5999 &
+            sleep 2
+            mapreduce-worker --host localhost --port 6001 --manager-host localhost --manager-port 6000 --manager-hb-port 5999 &
+            mapreduce-worker --host localhost --port 6002 --manager-host localhost --manager-port 6000 --manager-hb-port 5999 &
+        fi
         ;;
     *)
         usage
